Repository javascript-spec/hacktoberfest2021, pull requests merged in 2020-10, with the labels that each got.

#4 Structure the moving_lamp.css
  Moving Lamp/moving_lamp.css
Labels: enhancement

#3 structure moving_lamp.html
  Moving Lamp/moving_lamp.html
Labels: good first issue

#5 Create main.rb
  main.rb
Labels: hacktoberfest-accepted

#7 Create MatrixMultiplication.r
  MatrixMultiplication.r
Labels: hacktoberfest-accepted

#8 Create LengthOfPointer.go
  LengthOfPointer.go
Labels: hacktoberfest-accepted

#9 A new preloader added
  Preloader/index.css
  Preloader/index.html
Labels: hacktoberfest-accepted
