Repository javascript-spec/hacktoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#10 added animated sidebar at main folder
  Animated Sidebar/index.html
  Animated Sidebar/script.js
  Animated Sidebar/styles.css
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#11 Added the Age Calculator
  Age Calculator/index.html
  Age Calculator/script.js
  Age Calculator/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#12 Add Bookshelf Apps
  Bookshelf Apps/addDeleteUpdate.js
  Bookshelf Apps/index.css
  Bookshelf Apps/index.html
  Bookshelf Apps/script.js
  Bookshelf Apps/storage.js
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#13 Update README.md
  README.md
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#15 Age in days converter
  Age in days coverter/index.html
  Age in days coverter/script.js
  Age in days coverter/style.css
Labels: hacktoberfest-accepted, Hacktoberfest2021

#17 This script extracts table names from view script
  extract_tables.py
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#19 clock using html css js
  clock/clock.css
  clock/clock.html
  clock/clock.js
  clock/clock.png
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#20 Hide navbar on Scroll down and show on Scroll up
  Hide navbar on scroll down and show on scroll up/index.html
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#18 ecom_website
  ecommerce/README.md
  ecommerce/img/cat1.jpg
  ecommerce/img/cat2.jpg
  ecommerce/img/cat3.jpg
  ecommerce/img/cat4.jpg
  ecommerce/img/cat5.jpg
  ecommerce/img/product1.jpg
  ecommerce/img/product2.jpg
  ecommerce/img/product3.jpg
  ecommerce/img/product4.jpg
  ecommerce/img/product5.jpg
  ecommerce/img/product6.jpg
  ecommerce/img/product7.jpg
  ecommerce/img/undraw_deliveries_131a-removebg-preview.png
  ecommerce/index.html
  ecommerce/index.js
  ecommerce/sreenshot.png
  ecommerce/styles.css
Labels: hacktoberfest-accepted, Hacktoberfest2021

#21 [added] Dijkstra's Algorithm in Java
  Dijsktra's Algorithm in Java/DijsktraAlgo.java
Labels: enhancement, hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#25 Added index.html & style.css files for Liquid Drops Preloader Animation
  Liquid Drops Preloader Animation/index.html
  Liquid Drops Preloader Animation/style.css
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#24 Add Glashmorphism tilted card
  glassmorph card/glassmorph.css
  glassmorph card/glassmorph.html
  glassmorph card/project1.svg
  glassmorph card/vanilla-tilt.js
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#22 Added Celsius to Fahrenheit Converter
  Temperature/coverter.js
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#27 Add a dice game
  Dice Game/.DS_Store
  Dice Game/dicee.html
  Dice Game/images/dice1.png
  Dice Game/images/dice2.png
  Dice Game/images/dice3.png
  Dice Game/images/dice4.png
  Dice Game/images/dice5.png
  Dice Game/images/dice6.png
  Dice Game/index.js
  Dice Game/styles.css
Labels: enhancement, hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#26 Added a Drawing_App
  Drawing_App/index.html
  Drawing_App/script.js
  Drawing_App/style.css
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#28 [file added] implemented A* Search algorithm in CPP
  A Star Path Finding Visualizier/path_finder.cpp
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#31 Build the multiple items per slide in bootstrap carousel
  Carousel Animation/index.html
  Carousel Animation/script.js
  Carousel Animation/styles.css
  Twitter Dark Mode Skeleton Loading/index.html
  Twitter Dark Mode Skeleton Loading/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#30 Added Rainbow Loader
  Rainbow Loader/index.html
  Rainbow Loader/styles.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#33 Added Typing Effect Animation using CSS
  CSS Typing Effect/index.html
  CSS Typing Effect/styles.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#37 ToDo app with ReactJS
  ToDo App/README.md
  ToDo App/package-lock.json
  ToDo App/package.json
  ToDo App/public/favicon.ico
  ToDo App/public/index.html
  ToDo App/src/App.css
  ToDo App/src/App.js
  ToDo App/src/assets/logo.png
  ToDo App/src/components/ToDo.css
  ToDo App/src/components/ToDo.js
  ToDo App/src/components/ToDoItem.css
  ToDo App/src/components/ToDoItem.js
  ToDo App/src/index.js
  ToDo App/src/logo.svg
  ToDo App/yarn.lock
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#38 Added calculator app made using vanilla js
  calculator/cj.js
  calculator/cs.css
  calculator/index.html
Labels: hacktoberfest-accepted, Hacktoberfest2021

#36 Added a Happy Birthday Wisher
  HappyBirthdayWisher/HBD_wisher.html
Labels: hacktoberfest-accepted, Hacktoberfest

#34 Added Java project
  Java Garden/Bush.java
  Java Garden/BushGarden.java
  Java Garden/Flower.java
  Java Garden/FlowerBushGarden.java
  Java Garden/FlowerGarden.java
  Java Garden/FlowerGardenTest.java
  Java Garden/FlowerTest.java
  Java Garden/Garden.java
  Java Garden/GardenTest.java
  Java Garden/Plant.java
  Java Garden/PlantInterface.java
Labels: hacktoberfest-accepted, Hacktoberfest2021

#35 Create Linked list.py
  Linked list.py
Labels: hacktoberfest-accepted, Hacktoberfest2021

#47 Fun game - Whack A Mole
  Whack-A-Mole/css/styles.css
  Whack-A-Mole/images/dirt.svg
  Whack-A-Mole/images/mole-game.png
  Whack-A-Mole/images/mole.svg
  Whack-A-Mole/index.html
  Whack-A-Mole/js/main.js
  Whack-A-Mole/screenshot/screenshot.png
Labels: hacktoberfest-accepted, Hacktoberfest

#46 Switch Dark and Light Mode
  Dark&Light Mode User Card/index.html
  Dark&Light Mode User Card/main.js
  Dark&Light Mode User Card/style.css
  Dark&Light Mode User Card/user.png
Labels: hacktoberfest-accepted, Hacktoberfest2021

#42 Added a Slider image background which changes bg image in every 2 sec…
  slider-image-background/assets/bg-1.jpg
  slider-image-background/assets/bg-2.jpg
  slider-image-background/assets/bg-3.jpg
  slider-image-background/assets/bg-4.jpg
  slider-image-background/assets/bg-5.jpg
  slider-image-background/assets/bg-6.jpg
  slider-image-background/bg.css
  slider-image-background/bg.html
  slider-image-background/bg.js
  slider-image-background/bg1.js
Labels: enhancement, hacktoberfest-accepted, Hacktoberfest2021

#41 Added a Tic Tac Toe game
  Tic Tac Toe/Readme.txt
  Tic Tac Toe/index.html
  Tic Tac Toe/main.js
  Tic Tac Toe/style.css
Labels: Hacktoberfest2021

#44 Added a Toggle Bar
  Toggle_Menu/index.html
  Toggle_Menu/index.js
  Toggle_Menu/style.css
Labels: hacktoberfest-accepted, Hacktoberfest2021

#40 Added Weather App
  weather app/README.md
  weather app/index.html
  weather app/script.js
  weather app/style.css
  weather app/wback.jpg
  weather app/weather.png
Labels: Hacktoberfest2021

#50 hackerrank_Automation.js
  hackerrank_Automation.js
Labels: hacktoberfest-accepted, Hacktoberfest, Hacktoberfest2021

#48 Random Color Generator
  Js-RandomColourGenerator/favicon-32x32.png
  Js-RandomColourGenerator/index.html
  Js-RandomColourGenerator/script.js
  Js-RandomColourGenerator/style.css
Labels: hacktoberfest-accepted

#49 Google search clone
  1-google-search-page/css/styles.css
  1-google-search-page/image/bars.png
  1-google-search-page/image/google.png
  1-google-search-page/image/mic.png
  1-google-search-page/image/search.png
  1-google-search-page/index.html
Labels: hacktoberfest-accepted, Hacktoberfest2021

#60 readme file modified and project added
  Movieverse/index.html
  Movieverse/main.js
  Movieverse/style.css
  README.md
Labels: hacktoberfest-accepted, Hacktoberfest2021

#57 Checkout Page of a music website (Order summary).
  Checkout page/images/favicon-32x32.png
  Checkout page/images/icon-music.svg
  Checkout page/images/illustration-hero.svg
  Checkout page/images/pattern-background-desktop.svg
  Checkout page/images/pattern-background-mobile.svg
  Checkout page/index.html
  Checkout page/mobile.css
  Checkout page/style.css
Labels: hacktoberfest-accepted

#56 Added QR code generator app
  QR Code Generator/index.html
Labels: hacktoberfest-accepted

#54 Create JavaScript_Calculator.html
  Calculator/JavaScript_Calculator.html
Labels: hacktoberfest-accepted

#52 Rock-Paper-Scissors
  Rock-Paper-Scissors/README.md
  Rock-Paper-Scissors/css/styles.css
  Rock-Paper-Scissors/images/icon.png
  Rock-Paper-Scissors/images/loading-icon-transparent-background-12.jpg
  Rock-Paper-Scissors/images/paper.png
  Rock-Paper-Scissors/images/record.gif
  Rock-Paper-Scissors/images/rock.png
  Rock-Paper-Scissors/images/scissors.png
  Rock-Paper-Scissors/index.html
  Rock-Paper-Scissors/js/app.js
Labels: hacktoberfest-accepted, Hacktoberfest2021
